version: 0.2

env:
  variables:
    AWS_SDK_LOAD_CONFIG: "1"
    PYTHONUNBUFFERED: "1"

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - apt-get update -y
      - apt-get install -y python3.11-full python3.11-dev python3-pip libpq-dev
      - python3.11 -m pip install --upgrade pip
      - curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 -
      - ln -s /opt/poetry/bin/poetry /usr/local/bin/poetry
      - npm install -g yarn
      
  pre_build:
    commands:
      - |
        cat << EOF > .env
        DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
        DEBUG=${DEBUG}
        DB_NAME=${DB_NAME}
        DB_USER=${DB_USER}
        DB_PASSWORD=${DB_PASSWORD}
        DB_HOST=${DB_HOST}
        DB_PORT=${DB_PORT}
        ALLOWED_HOSTS=${ALLOWED_HOSTS}
        EOF
      - poetry config virtualenvs.create false
      - poetry install --no-interaction --no-ansi
      - cd pathfinders-client
      - yarn install
      - cd ..
      
  build:
    commands:
      - cd pathfinders-client
      - yarn build
      - cd ..
      - poetry run python manage.py collectstatic --noinput --no-input
      
  post_build:
    commands:
      - poetry run python manage.py migrate --noinput
      - zip -r deployment.zip . -x "*.git*" "*.pytest_cache*" "*__pycache__*" "*.env*" "pathfinders-client/node_modules/*" "pathfinders-client/.next/*"

artifacts:
  files:
    - deployment.zip
    - appspec.yml
    - scripts/**/*
  discard-paths: no