version: 0.2

env:
  secrets-manager:
    DB_USER: "pathfinders_db:username"
    DB_PASSWORD: "pathfinders_db:password"
    DB_HOST: "pathfinders_db:host"
    DB_NAME: "pathfinders_db:dbname"
    GITHUB_TOKEN: "Pathfinders_GitHub_Access:token"
  variables:
    DJANGO_SETTINGS_MODULE: "pathfinders_project.settings"
    DEBUG: "False"
    ALLOWED_HOSTS: "pathfindersgifts.com,www.pathfindersgifts.com,13.61.197.147"

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - apt-get update
      - apt-get install -y python3-pip python3-dev libpq-dev
      - pip install --upgrade pip
      - curl -sSL https://install.python-poetry.org | python3 -
      - npm install -g yarn
      
  pre_build:
    commands:
      # Create temporary env file for build
      - |
        cat << EOF > .env
        DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
        DEBUG=${DEBUG}
        DB_NAME=${DB_NAME}
        DB_USER=${DB_USER}
        DB_PASSWORD=${DB_PASSWORD}
        DB_HOST=${DB_HOST}
        ALLOWED_HOSTS=${ALLOWED_HOSTS}
        EOF
      # Install backend dependencies
      - poetry config virtualenvs.create false
      - poetry install --no-interaction --no-ansi
      # Install frontend dependencies
      - cd pathfinders-client
      - yarn install
      - cd ..
      
  build:
    commands:
      # Build frontend
      - cd pathfinders-client
      - yarn build
      # Collect static files for Django
      - cd ..
      - poetry run python manage.py collectstatic --noinput --no-input
      
  post_build:
    commands:
      # Run database migrations
      - poetry run python manage.py migrate --noinput
      # Create deployment package
      - zip -r deployment.zip . -x "*.git*" "*.pytest_cache*" "*__pycache__*" "*.env*" "pathfinders-client/node_modules/*" "pathfinders-client/.next/*"

artifacts:
  files:
    - deployment.zip
    - appspec.yml
    - scripts/**/*
  discard-paths: no 