# Generated by Django 5.1.5 on 2025-08-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_payment_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="message",
            field=models.TextField(blank=True, help_text="Optional message from donor"),
        ),
        migrations.AddField(
            model_name="payment",
            name="mtn_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe_card", "Stripe Card Payment"),
                    ("mtn_mobile_money", "MTN Mobile Money"),
                ],
                default="stripe_card",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("assessment", "Assessment Payment"),
                    ("donation", "Donation"),
                ],
                default="donation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
